apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
labels:
    app: {{ .Values.name }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}